### ISSUE TITLE
Containerisierung der React App

### ISSUE THREAD

**Issue by joshua-lehmann** [joshua-lehmann/SmashGrade#5]
Um eine einfache Ausführung der Frontend App zu ermöglichen, soll sie mithilfe von Docker containerisiert werden. So kann sie jeder simpel ausführen ohne Node oder sonstige Dependencies manuell zu installieren.
Es soll also ein Docker File erstellt werden, welches ein Docker Image für unsere react app erstellt. 

Guide als Inspiration: https://www.freecodecamp.org/news/how-to-dockerize-a-react-application/
Und hier ein Beispiel einer React App die bereits mit Docker läuft: https://github.com/joshua-lehmann/personen-verwaltung-gui/blob/master/Dockerfile
Die Links dienen nur als Inspiration, es soll die beste/aktuellste Methode verwendet werden um die react app als docker image bereit zu stellen.
Beispielsweise sollte node 18 LTS verwendet werden.

Das Image soll dann auf [GitHub gepusht und zur Verfügung gestellt](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images) werden. Später soll dieser Prozess in der Pipeline automatisiert werden.

**Comment by theGreyPilgrim42** [comment]
Wenn ein neues Tag und ein damit einhergehendes Release erstellt wird, dann wird mit dem `docker-build` Workflow automatisch zwei Images, eins für die `react-app` und eins für den `json-server` erstellt. 
Mit `docker-compose up -d` werden die Images automatisch gestartet und die React-App ist auf `localhost:80` und der JSON Server auf `localhost:3000` verfügbar.

Um Zugriff auf das GHCR Registry zu haben, müssen die folgenden Schritte [hier](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic) ausgeführt werden.

# ToDo:
- [ ] Docker Container für Backend Anbindung optimieren
- [ ] Beschreibung im Wiki ergänzen
- [x] Prüfen wie das neuste Image (Tag) gepullt werden kann
